/*
    Copyright 2026 Robin Zhang & Labs

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 */

#ifndef DGS_LFO_INTERFACE_H
#define DGS_LFO_INTERFACE_H

#include <QObject>
#include "digishow_interface.h"
#include "digishow_lfo.h"

class DgsLfoInterface : public DigishowInterface
{
    Q_OBJECT
public:
    explicit DgsLfoInterface(QObject *parent = nullptr);
    ~DgsLfoInterface() override;

    int openInterface() override;
    int closeInterface() override;
    int sendData(int endpointIndex, dgsSignalData data) override;

signals:

public slots:
    void onValueChanged(double value); // Received values generated by LFOs

private:

    QMap<int, DigishowLFO*> m_lfos;

    static QString getFunctionName(const QString & func);
    static DigishowLFO::LfoFunction getFunctionType(const QString & func);

    void updateMetadata_() override;

};

#endif // DGS_LFO_INTERFACE_H
